In [3]:
import pandas as pd
import os

In [11]:
customer_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Bronze\customers\customers.csv"
customers_df = pd.read_csv(customer_path)
customers_df.head()

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [23]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    object
 1   customer_name             200 non-null    object
 2   customer_type             200 non-null    object
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    object
 5   account_status            200 non-null    object
 6   contract_start_date       200 non-null    object
 7   annual_revenue_potential  200 non-null    int64
dtypes: int64(2), object(6)
memory usage: 12.6+ KB

In [17]:
customers_df.describe()

       credit_terms_days  annual_revenue_potential
count         200.000000              2.000000e+02
mean           37.650000              2.688237e+06
std            17.078815              1.454957e+06
min            15.000000              1.016410e+05
25%            30.000000              1.405872e+06
50%            30.000000              2.784584e+06
75%            60.000000              3.859272e+06
max            60.000000              4.990599e+06

In [19]:
customers_df.isnull().sum()

customer_id                 0
customer_name               0
customer_type               0
credit_terms_days           0
primary_freight_type        0
account_status              0
contract_start_date         0
annual_revenue_potential    0
dtype: int64

In [21]:
customers_df.columns

Index(['customer_id', 'customer_name', 'customer_type', 'credit_terms_days',
       'primary_freight_type', 'account_status', 'contract_start_date',
       'annual_revenue_potential'],
      dtype='object')

In [25]:
customers_df.shape

(200, 8)

In [29]:
customers_df["contract_start_date"] = pd.to_datetime(customers_df["contract_start_date"])

In [31]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    object
 1   customer_name             200 non-null    object
 2   customer_type             200 non-null    object
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    object
 5   account_status            200 non-null    object
 6   contract_start_date       200 non-null    datetime64[ns]
 7   annual_revenue_potential  200 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 12.6+ KB

In [33]:
customers_df["contract_start_date"] = pd.to_datetime(customers_df["contract_start_date"])

In [35]:
bronze_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Bronze"

In [37]:
import os

csv_files = os.listdir(bronze_path)
csv_files

['customers',
 'delivery_events',
 'desktop.ini',
 'drivers',
 'driver_monthly_metrics',
 'facilities',
 'fuel_purchases',
 'loads',
 'maintenance_records',
 'routes',
 'safety_incidents',
 'trailers',
 'trips',
 'trucks',
 'truck_utilization _metrics']

In [43]:
dataframes = {}

for folder in csv_files:
    folder_path =os.path.join(bronze_path , folder)
    if os.path.isdir(folder_path):

        file = os.listdir(folder_path)[0]
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)
        dataframes[folder] = df
print(dataframes.keys())

dict_keys(['customers', 'delivery_events', 'drivers', 'driver_monthly_metrics', 'facilities', 'fuel_purchases', 'loads', 'maintenance_records', 'routes', 'safety_incidents', 'trailers', 'trips', 'trucks', 'truck_utilization _metrics'])

In [45]:
dataframes["customers"].head()

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [47]:
dataframes["drivers"].head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [49]:
(os.listdir(bronze_path))

['customers',
 'delivery_events',
 'desktop.ini',
 'drivers',
 'driver_monthly_metrics',
 'facilities',
 'fuel_purchases',
 'loads',
 'maintenance_records',
 'routes',
 'safety_incidents',
 'trailers',
 'trips',
 'trucks',
 'truck_utilization _metrics']

In [59]:
dataframes = {}
for folder in os.listdir(bronze_path):

    if folder == "desktop.ini":
        continue
    folder_path = os.path.join(bronze_path , folder)
    if os.path.isdir(folder_path):
        file = os.listdir(folder_path)[0]
        file_path = os.path.join(folder_path,file)
        df = pd.read_csv(file_path)
        dataframes[folder] = df
print(dataframes.keys())

dict_keys(['customers', 'delivery_events', 'drivers', 'driver_monthly_metrics', 'facilities', 'fuel_purchases', 'loads', 'maintenance_records', 'routes', 'safety_incidents', 'trailers', 'trips', 'trucks', 'truck_utilization _metrics'])

In [61]:
for name,df in dataframes.items():
    print(f"{name}:{df.shape}")

customers:(200, 8)
delivery_events:(170820, 11)
drivers:(150, 12)
driver_monthly_metrics:(4464, 9)
facilities:(50, 9)
fuel_purchases:(196442, 11)
loads:(85410, 12)
maintenance_records:(2920, 12)
routes:(58, 9)
safety_incidents:(170, 15)
trailers:(180, 9)
trips:(85410, 12)
trucks:(120, 11)
truck_utilization _metrics:(3312, 10)