In [7]:
import pandas as pd
import os

In [8]:
silver_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Silver"

In [9]:
gold_dataframes = {}
for folder in os.listdir(silver_path):
    folder_path = os.path.join(silver_path, folder)
    if os.path.isdir(folder_path):
        file = os.listdir(folder_path)[0]
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)
        gold_dataframes[folder] = df
print(gold_dataframes.keys())

dict_keys(['customers', 'delivery_events', 'drivers', 'driver_monthly_metrics', 'facilities', 'fuel_purchases', 'loads', 'maintenance_records', 'routes', 'safety_incidents', 'trailers', 'trips', 'trucks', 'truck_utilization _metrics'])

In [10]:
drivers = gold_dataframes["drivers"]
driver_metrics = gold_dataframes["driver_monthly_metrics"]
drivers.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [11]:
print(drivers.columns.tolist())
print(driver_metrics.columns.tolist())

['driver_id', 'first_name', 'last_name', 'hire_date', 'termination_date', 'license_number', 'license_state', 'date_of_birth', 'home_terminal', 'employment_status', 'cdl_class', 'years_experience']
['driver_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'total_fuel_gallons', 'on_time_delivery_rate', 'average_idle_hours']

In [12]:
drivers.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [13]:
driver_metrics.head()

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,2022-04-01,19,28127,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,2022-05-01,14,16071,36256.82,6.35,2573.1,0.214,6.8

In [14]:
print(drivers.columns.tolist())

['driver_id', 'first_name', 'last_name', 'hire_date', 'termination_date', 'license_number', 'license_state', 'date_of_birth', 'home_terminal', 'employment_status', 'cdl_class', 'years_experience']

In [15]:
print(driver_metrics.columns.tolist())

['driver_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'total_fuel_gallons', 'on_time_delivery_rate', 'average_idle_hours']

In [16]:
driver_performance = pd.merge(
    drivers,
    driver_metrics,
    on="driver_id",
    how="left"
)
driver_performance.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-01-01,26.0,36620.0,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-02-01,9.0,13515.0,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-03-01,20.0,30361.0,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-04-01,19.0,28127.0,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-05-01,14.0,16071.0,36256.82,6.35,2573.1,0.214,6.8

In [17]:
driver_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4490 entries, 0 to 4489
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4490 non-null   object
 1   first_name             4490 non-null   object
 2   last_name              4490 non-null   object
 3   hire_date              4490 non-null   object
 4   termination_date       26 non-null     object
 5   license_number         4490 non-null   object
 6   license_state          4490 non-null   object
 7   date_of_birth          4490 non-null   object
 8   home_terminal          4490 non-null   object
 9   employment_status      4490 non-null   object
 10  cdl_class              4490 non-null   object
 11  years_experience       4490 non-null   int64
 12  month                  4464 non-null   object
 13  trips_completed        4464 non-null   float64
 14  total_miles            4464 non-null   float64
 15  total_revenue          4464 non-null   float64
 16  average_mpg            4464 non-null   float64
 17  total_fuel_gallons     4464 non-null   float64
 18  on_time_delivery_rate  4464 non-null   float64
 19  average_idle_hours     4464 non-null   float64
dtypes: float64(7), int64(1), object(12)
memory usage: 701.7+ KB

In [18]:
driver_summary = driver_performance.groupby(
    ["driver_id", "first_name", "last_name"]
).agg({
    "trips_completed": "sum",
    "total_miles": "sum",
    "total_revenue": "sum",
    "total_fuel_gallons": "sum",
    "average_mpg": "mean",
    "on_time_delivery_rate": "mean",
    "average_idle_hours": "mean"
}).reset_index()

driver_summary.head()

,driver_id,first_name,last_name,trips_completed,total_miles,total_revenue,total_fuel_gallons,average_mpg,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,632.0,930236.0,1985683.26,144705.9,6.484722,0.454167,7.036111
1,DRV00002,William,Martin,662.0,943246.0,2073621.50,146600.7,6.505000,0.468389,7.108333
2,DRV00003,Charles,Hernandez,677.0,1010235.0,2146977.47,155897.8,6.539444,0.450806,6.797222
3,DRV00004,Barbara,Brown,659.0,982625.0,2119361.45,152143.0,6.517222,0.428333,7.002778
4,DRV00005,Mary,Martinez,643.0,923128.0,2022357.46,143472.8,6.512222,0.454056,7.136111

In [31]:
driver_summary = driver_performance.groupby(
    ["driver_id", "first_name", "last_name"]
).agg({
    "trips_completed": "sum",
    "total_miles": "sum",
    "total_revenue": "sum",
    "total_fuel_gallons": "sum",
    "average_mpg": "mean",
    "on_time_delivery_rate": "mean",
    "average_idle_hours": "mean"
}).reset_index()
driver_summary.head()

,driver_id,first_name,last_name,trips_completed,total_miles,total_revenue,total_fuel_gallons,average_mpg,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,632.0,930236.0,1985683.26,144705.9,6.484722,0.454167,7.036111
1,DRV00002,William,Martin,662.0,943246.0,2073621.50,146600.7,6.505000,0.468389,7.108333
2,DRV00003,Charles,Hernandez,677.0,1010235.0,2146977.47,155897.8,6.539444,0.450806,6.797222
3,DRV00004,Barbara,Brown,659.0,982625.0,2119361.45,152143.0,6.517222,0.428333,7.002778
4,DRV00005,Mary,Martinez,643.0,923128.0,2022357.46,143472.8,6.512222,0.454056,7.136111

In [33]:
driver_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              150 non-null    object
 1   first_name             150 non-null    object
 2   last_name              150 non-null    object
 3   trips_completed        150 non-null    float64
 4   total_miles            150 non-null    float64
 5   total_revenue          150 non-null    float64
 6   total_fuel_gallons     150 non-null    float64
 7   average_mpg            124 non-null    float64
 8   on_time_delivery_rate  124 non-null    float64
 9   average_idle_hours     124 non-null    float64
dtypes: float64(7), object(3)
memory usage: 11.8+ KB

In [37]:
gold_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Gold"

In [39]:
import os

driver_summary_folder = os.path.join(gold_path, "driver_performance_summary")
os.makedirs(driver_summary_folder, exist_ok=True)

driver_summary.to_csv(
    os.path.join(driver_summary_folder, "driver_performance_summary.csv"),
    index=False
)

print("✅ Driver Performance Summary saved successfully!")

✅ Driver Performance Summary saved successfully!

In [41]:
import pandas as pd

customers = pd.read_csv("../Silver/customers/customers.csv")
customers.head()

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [43]:
customer_summary = customers.groupby(
    ["customer_id", "customer_name", "customer_type"],
    as_index=False
).agg(
    annual_revenue=("annual_revenue_potential", "sum")
)

customer_summary.head()

  customer_id          customer_name customer_type  annual_revenue
0   CUST00001        Metro Wholesale     Dedicated          985117
1   CUST00002        National Retail      Contract         4936566
2   CUST00003         XYZ Industries      Contract         3102814
3   CUST00004          American Corp      Contract         3948027
4   CUST00005  American Distribution          Spot         3682564

In [45]:
customer_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     200 non-null    object
 1   customer_name   200 non-null    object
 2   customer_type   200 non-null    object
 3   annual_revenue  200 non-null    int64
dtypes: int64(1), object(3)
memory usage: 6.4+ KB

In [47]:
import os

gold_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Gold\customer_revenue_summary"

os.makedirs(gold_path, exist_ok=True)

customer_summary.to_csv(
    os.path.join(gold_path, "customer_revenue_summary.csv"),
    index=False
)

print("✅ Customer Revenue Summary saved successfully!")

✅ Customer Revenue Summary saved successfully!

In [55]:
import os
print(os.getcwd())

C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Notebooks

In [59]:
os.listdir("../silver")

['customers',
 'delivery_events',
 'drivers',
 'driver_monthly_metrics',
 'facilities',
 'fuel_purchases',
 'loads',
 'maintenance_records',
 'routes',
 'safety_incidents',
 'trailers',
 'trips',
 'trucks',
 'truck_utilization _metrics']

In [63]:
import os
for item in os.listdir("../Silver"):
    print(item)

customers
delivery_events
drivers
driver_monthly_metrics
facilities
fuel_purchases
loads
maintenance_records
routes
safety_incidents
trailers
trips
trucks
truck_utilization _metrics

In [65]:
import glob
print(glob.glob("../Silver/*"))

['../Silver\\customers', '../Silver\\delivery_events', '../Silver\\drivers', '../Silver\\driver_monthly_metrics', '../Silver\\facilities', '../Silver\\fuel_purchases', '../Silver\\loads', '../Silver\\maintenance_records', '../Silver\\routes', '../Silver\\safety_incidents', '../Silver\\trailers', '../Silver\\trips', '../Silver\\trucks', '../Silver\\truck_utilization _metrics']

In [67]:
print(glob.glob("../Silver/truck*"))

['../Silver\\trucks', '../Silver\\truck_utilization _metrics']

In [73]:
import os

print(os.listdir("../Silver\\truck_utilization _metrics"))

['truck_utilization _metrics.csv']

In [81]:
truck_metrics = pd.read_csv("../Silver\\truck_utilization _metrics/truck_utilization _metrics.csv")

In [84]:
truck_metrics.head()

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,2022-01-01,22,39269,84792.02,6.78,2,4380.98,63.1,0.710
1,TRK00001,2022-02-01,27,40787,88809.05,6.23,0,0.00,0.0,0.964
2,TRK00001,2022-03-01,34,57422,120453.71,6.49,0,0.00,0.0,1.097
3,TRK00001,2022-04-01,20,34428,73531.28,6.50,2,3548.15,71.8,0.667
4,TRK00001,2022-05-01,16,20851,40791.53,6.38,1,1969.42,43.9,0.516

In [88]:
print(truck_metrics.columns.tolist())

['truck_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'maintenance_events', 'maintenance_cost', 'downtime_hours', 'utilization_rate']

In [90]:
truck_summary = truck_metrics.groupby("truck_id").agg({
    "trips_completed": "sum",
    "total_miles": "sum",
    "total_revenue": "sum",
    "average_mpg": "mean",
    "maintenance_events": "sum",
    "maintenance_cost": "sum",
    "downtime_hours": "sum",
    "utilization_rate": "mean"
}).reset_index()

truck_summary.head()

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,951,1356397,2896338.17,6.488611,24,51775.99,713.2,0.867139
1,TRK00002,887,1270572,2712361.86,6.492500,27,54869.04,665.3,0.809583
2,TRK00004,929,1309547,2803602.13,6.498611,22,38561.82,483.2,0.847111
3,TRK00006,878,1278551,2778546.55,6.485556,26,50780.83,587.7,0.801778
4,TRK00007,922,1336736,2887748.17,6.485833,20,25868.97,415.7,0.841528

In [92]:
print(truck_metrics.columns.tolist())

['truck_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'maintenance_events', 'maintenance_cost', 'downtime_hours', 'utilization_rate']

In [94]:
import os

gold_path = "../Gold/truck_summary"
os.makedirs(gold_path, exist_ok=True)

In [96]:
truck_summary.to_csv(
    "../Gold/truck_summary/truck_summary.csv",
    index=False
)

print("✅ Truck Summary saved successfully!")

✅ Truck Summary saved successfully!

In [98]:
import os

print(os.listdir("../Gold/truck_summary"))

['truck_summary.csv']

In [100]:
routes = pd.read_csv("../Silver/routes/routes.csv")
loads = pd.read_csv("../Silver/loads/loads.csv")

In [102]:
route_summary = loads.merge(routes, on="route_id", how="left")

In [108]:
print(loads.columns.tolist())

['load_id', 'customer_id', 'route_id', 'load_date', 'load_type', 'weight_lbs', 'pieces', 'revenue', 'fuel_surcharge', 'accessorial_charges', 'load_status', 'booking_type']

In [110]:
print(routes.columns.tolist())

['route_id', 'origin_city', 'origin_state', 'destination_city', 'destination_state', 'typical_distance_miles', 'base_rate_per_mile', 'fuel_surcharge_rate', 'typical_transit_days']

In [112]:
route_summary = loads.merge(routes, on="route_id", how="left")

route_summary = route_summary.groupby("route_id").agg({
    "load_id": "count",
    "revenue": "sum",
    "typical_distance_miles": "mean"
}).reset_index()

route_summary.rename(columns={
    "load_id": "total_loads",
    "revenue": "total_revenue",
    "typical_distance_miles": "average_distance"
}, inplace=True)

route_summary.head()

   route_id  total_loads  total_revenue  average_distance
0  RTE00001         1456     1675362.80             677.0
1  RTE00002         1481     2154291.12             697.0
2  RTE00003         1496     7621380.80            2003.0
3  RTE00004         1459     5418160.40            2017.0
4  RTE00005         1479     6236094.68            1749.0

In [114]:
import os

os.makedirs("../Gold/route_summary", exist_ok=True)

route_summary.to_csv(
    "../Gold/route_summary/route_summary.csv",
    index=False
)

print("✅ Route Summary saved successfully!")

✅ Route Summary saved successfully!

In [1]:
import os

gold_path = "../Gold"

for root, dirs, files in os.walk(gold_path):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

../Gold\customer_revenue_summary\customer_revenue_summary.csv
../Gold\driver_performance_summary\driver_performance_summary.csv
../Gold\route_summary\route_summary.csv
../Gold\truck_summary\truck_summary.csv

In [3]:
import pandas as pd

customer_summary = pd.read_csv(
    "../Gold/customer_revenue_summary/customer_revenue_summary.csv"
)

driver_summary = pd.read_csv(
    "../Gold/driver_performance_summary/driver_performance_summary.csv"
)

route_summary = pd.read_csv(
    "../Gold/route_summary/route_summary.csv"
)

truck_summary = pd.read_csv(
    "../Gold/truck_summary/truck_summary.csv"
)

print("Customer Summary:", customer_summary.shape)
print("Driver Summary:", driver_summary.shape)
print("Route Summary:", route_summary.shape)
print("Truck Summary:", truck_summary.shape)

Customer Summary: (200, 4)
Driver Summary: (150, 10)
Route Summary: (58, 4)
Truck Summary: (92, 9)

In [5]:
# Gold Layer Data Quality Validation

print("=== Gold Layer Data Quality Check ===")

# 1. Duplicate check
print("\nDuplicate Records:")
print("Customer Summary:", customer_summary.duplicated().sum())
print("Driver Summary:", driver_summary.duplicated().sum())
print("Route Summary:", route_summary.duplicated().sum())
print("Truck Summary:", truck_summary.duplicated().sum())

# 2. Null check
print("\nNull Values:")
print("Customer Summary:")
print(customer_summary.isnull().sum())

print("\nDriver Summary:")
print(driver_summary.isnull().sum())

print("\nRoute Summary:")
print(route_summary.isnull().sum())

print("\nTruck Summary:")
print(truck_summary.isnull().sum())

=== Gold Layer Data Quality Check ===

Duplicate Records:
Customer Summary: 0
Driver Summary: 0
Route Summary: 0
Truck Summary: 0

Null Values:
Customer Summary:
customer_id       0
customer_name     0
customer_type     0
annual_revenue    0
dtype: int64

Driver Summary:
driver_id                 0
first_name                0
last_name                 0
trips_completed           0
total_miles               0
total_revenue             0
total_fuel_gallons        0
average_mpg              26
on_time_delivery_rate    26
average_idle_hours       26
dtype: int64

Route Summary:
route_id            0
total_loads         0
total_revenue       0
average_distance    0
dtype: int64

Truck Summary:
truck_id              0
trips_completed       0
total_miles           0
total_revenue         0
average_mpg           0
maintenance_events    0
maintenance_cost      0
downtime_hours        0
utilization_rate      0
dtype: int64

In [7]:
# Replace missing driver performance metrics with 0

driver_summary["average_mpg"] = driver_summary["average_mpg"].fillna(0)

driver_summary["on_time_delivery_rate"] = driver_summary["on_time_delivery_rate"].fillna(0)

driver_summary["average_idle_hours"] = driver_summary["average_idle_hours"].fillna(0)

print("Missing values replaced with 0 successfully!")

Missing values replaced with 0 successfully!

In [9]:
print(driver_summary[[
    "average_mpg",
    "on_time_delivery_rate",
    "average_idle_hours"
]].isnull().sum())

average_mpg              0
on_time_delivery_rate    0
average_idle_hours       0
dtype: int64

In [11]:
# Gold Layer Business Validation Checks

print("=== Gold Layer Business Validation ===")

# Customer Revenue Validation
print("\nCustomer Revenue:")
print("Minimum Revenue:", customer_summary["annual_revenue"].min())
print("Maximum Revenue:", customer_summary["annual_revenue"].max())

# Driver Performance Validation
print("\nDriver Performance:")
print("Minimum Trips:", driver_summary["trips_completed"].min())
print("Maximum Trips:", driver_summary["trips_completed"].max())

print("Minimum Total Miles:", driver_summary["total_miles"].min())
print("Maximum Total Miles:", driver_summary["total_miles"].max())

# Route Validation
print("\nRoute Performance:")
print("Minimum Loads:", route_summary["total_loads"].min())
print("Maximum Loads:", route_summary["total_loads"].max())

print("Minimum Revenue:", route_summary["total_revenue"].min())
print("Maximum Revenue:", route_summary["total_revenue"].max())

# Truck Validation
print("\nTruck Performance:")
print("Minimum Trips:", truck_summary["trips_completed"].min())
print("Maximum Trips:", truck_summary["trips_completed"].max())

print("Minimum Revenue:", truck_summary["total_revenue"].min())
print("Maximum Revenue:", truck_summary["total_revenue"].max())

=== Gold Layer Business Validation ===

Customer Revenue:
Minimum Revenue: 101641
Maximum Revenue: 4990599

Driver Performance:
Minimum Trips: 0.0
Maximum Trips: 749.0
Minimum Total Miles: 0.0
Maximum Total Miles: 1074677.0

Route Performance:
Minimum Loads: 1386
Maximum Loads: 1628
Minimum Revenue: 217573.05
Maximum Revenue: 10069054.22

Truck Performance:
Minimum Trips: 831
Maximum Trips: 977
Minimum Revenue: 2532045.68
Maximum Revenue: 3045707.57

In [13]:
# Save updated Driver Summary after null handling

driver_summary.to_csv(
    "../Gold/driver_performance_summary/driver_performance_summary.csv",
    index=False
)

print("✅ Updated Driver Performance Summary saved successfully!")

✅ Updated Driver Performance Summary saved successfully!

In [15]:
# Final Gold Layer Data Quality Check

print("=== FINAL GOLD LAYER DATA QUALITY CHECK ===")

gold_tables = {
    "Customer Summary": customer_summary,
    "Driver Summary": driver_summary,
    "Route Summary": route_summary,
    "Truck Summary": truck_summary
}

for name, df in gold_tables.items():

    print(f"\n{name}")
    print("-" * 40)

    print("Rows:", len(df))
    print("Columns:", len(df))
    print("Duplicate Rows:", df.duplicated().sum())
    print("Total Null Values:", df.isnull().sum().sum())

print("\n✅ Final Gold Layer Data Quality Check Completed!")

=== FINAL GOLD LAYER DATA QUALITY CHECK ===

Customer Summary
----------------------------------------
Rows: 200
Columns: 200
Duplicate Rows: 0
Total Null Values: 0

Driver Summary
----------------------------------------
Rows: 150
Columns: 150
Duplicate Rows: 0
Total Null Values: 0

Route Summary
----------------------------------------
Rows: 58
Columns: 58
Duplicate Rows: 0
Total Null Values: 0

Truck Summary
----------------------------------------
Rows: 92
Columns: 92
Duplicate Rows: 0
Total Null Values: 0

✅ Final Gold Layer Data Quality Check Completed!

In [17]:
print("=== DAY 7: GOLD LAYER BUSINESS INSIGHTS ===")

print("\nCustomer Summary:")
display(customer_summary.head())

print("\nDriver Performance Summary:")
display(driver_summary.head())

print("\nRoute Summary:")
display(route_summary.head())

print("\nTruck Summary:")
display(truck_summary.head())

=== DAY 7: GOLD LAYER BUSINESS INSIGHTS ===

Customer Summary:

  customer_id          customer_name customer_type  annual_revenue
0   CUST00001        Metro Wholesale     Dedicated          985117
1   CUST00002        National Retail      Contract         4936566
2   CUST00003         XYZ Industries      Contract         3102814
3   CUST00004          American Corp      Contract         3948027
4   CUST00005  American Distribution          Spot         3682564

Driver Performance Summary:

,driver_id,first_name,last_name,trips_completed,total_miles,total_revenue,total_fuel_gallons,average_mpg,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,632.0,930236.0,1985683.26,144705.9,6.484722,0.454167,7.036111
1,DRV00002,William,Martin,662.0,943246.0,2073621.50,146600.7,6.505000,0.468389,7.108333
2,DRV00003,Charles,Hernandez,677.0,1010235.0,2146977.47,155897.8,6.539444,0.450806,6.797222
3,DRV00004,Barbara,Brown,659.0,982625.0,2119361.45,152143.0,6.517222,0.428333,7.002778
4,DRV00005,Mary,Martinez,643.0,923128.0,2022357.46,143472.8,6.512222,0.454056,7.136111

Route Summary:

   route_id  total_loads  total_revenue  average_distance
0  RTE00001         1456     1675362.80             677.0
1  RTE00002         1481     2154291.12             697.0
2  RTE00003         1496     7621380.80            2003.0
3  RTE00004         1459     5418160.40            2017.0
4  RTE00005         1479     6236094.68            1749.0

Truck Summary:

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,951,1356397,2896338.17,6.488611,24,51775.99,713.2,0.867139
1,TRK00002,887,1270572,2712361.86,6.492500,27,54869.04,665.3,0.809583
2,TRK00004,929,1309547,2803602.13,6.498611,22,38561.82,483.2,0.847111
3,TRK00006,878,1278551,2778546.55,6.485556,26,50780.83,587.7,0.801778
4,TRK00007,922,1336736,2887748.17,6.485833,20,25868.97,415.7,0.841528

In [21]:
print("=== DAY 7: GOLD LAYER BUSINESS INSIGHTS ===")

# Top 10 Customers by Revenue
top_customers = customer_summary.sort_values(
    by="annual_revenue",
    ascending=False
).head(10)

print("\nTop 10 Customers by Revenue:")
display(top_customers)

=== DAY 7: GOLD LAYER BUSINESS INSIGHTS ===

Top 10 Customers by Revenue:

    customer_id         customer_name customer_type  annual_revenue
194   CUST00195   First Manufacturing          Spot         4990599
62    CUST00063        Superior Group     Dedicated         4983476
1     CUST00002       National Retail      Contract         4936566
81    CUST00082      Global Logistics          Spot         4934218
77    CUST00078     Premier Wholesale          Spot         4933788
146   CUST00147             ABC Group          Spot         4931991
108   CUST00109  Global Manufacturing      Contract         4925587
52    CUST00053    Elite Supply Chain          Spot         4895027
120   CUST00121              ABC Corp          Spot         4893591
136   CUST00137      First Industries     Dedicated         4892669

In [23]:
# Top 10 Drivers by Revenue

top_drivers = driver_summary.sort_values(
    by="total_revenue",
    ascending=False
).head(10)

print("\nTop 10 Drivers by Revenue:")
display(top_drivers)

Top 10 Drivers by Revenue:

,driver_id,first_name,last_name,trips_completed,total_miles,total_revenue,total_fuel_gallons,average_mpg,on_time_delivery_rate,average_idle_hours
50,DRV00051,Linda,Davis,723.0,1074677.0,2311844.30,167024.2,6.503889,0.434222,7.041667
107,DRV00108,Joseph,Jones,735.0,1073445.0,2311327.90,166238.4,6.516389,0.477167,7.172222
58,DRV00059,Barbara,Gonzalez,729.0,1064844.0,2305056.60,164582.5,6.516944,0.459667,7.030556
15,DRV00016,Thomas,Gonzalez,712.0,1042631.0,2278574.88,161679.1,6.490278,0.450111,7.102778
18,DRV00019,Robert,Jackson,749.0,1060268.0,2275654.76,165029.7,6.466667,0.449194,7.022222
126,DRV00127,Thomas,Gonzalez,702.0,1047108.0,2272317.62,162594.5,6.499167,0.420556,7.005556
148,DRV00149,Linda,Jones,721.0,1059718.0,2269105.67,164156.8,6.494722,0.452222,6.961111
146,DRV00147,Richard,Garcia,705.0,1039157.0,2256066.92,161429.3,6.495000,0.446944,6.952778
84,DRV00085,Linda,Wilson,703.0,1034233.0,2229521.23,160210.2,6.508611,0.453889,6.825000
86,DRV00087,William,Anderson,725.0,1029613.0,2214003.33,159277.4,6.516111,0.419056,6.894444

In [27]:
# Top 10 Routes by Revenue

top_routes = route_summary.sort_values(
    by="total_revenue",
    ascending=False
).head(10)

print("\nTop 10 Routes by Revenue:")
display(top_routes)

Top 10 Routes by Revenue:

    route_id  total_loads  total_revenue  average_distance
15  RTE00016         1465    10069054.22            2729.0
43  RTE00044         1410     9979091.72            2627.0
11  RTE00012         1507     9757537.38            2389.0
47  RTE00048         1525     9586536.90            2332.0
28  RTE00029         1467     9516077.71            2623.0
45  RTE00046         1534     9501202.04            2269.0
41  RTE00042         1447     9070885.01            2623.0
29  RTE00030         1445     7681556.33            2147.0
2   RTE00003         1496     7621380.80            2003.0
20  RTE00021         1473     7595328.46            2108.0

In [29]:
# Top 10 Trucks by Revenue

top_trucks = truck_summary.sort_values(
    by="total_revenue",
    ascending=False
).head(10)

print("\nTop 10 Trucks by Revenue:")
display(top_trucks)

Top 10 Trucks by Revenue:

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
32,TRK00044,971,1403922,3045707.57,6.500833,38,69825.23,1080.4,0.885250
82,TRK00107,930,1389705,3022073.78,6.488056,17,31131.25,341.2,0.847111
30,TRK00041,965,1404001,3017320.99,6.509722,25,59685.24,524.7,0.879583
41,TRK00055,977,1417530,2997124.44,6.477778,29,60433.32,689.5,0.890667
39,TRK00053,964,1378108,2990269.38,6.477222,27,50297.23,635.0,0.878889
12,TRK00015,961,1386604,2979377.79,6.497222,21,33711.95,562.5,0.877194
19,TRK00025,963,1370297,2942525.23,6.484722,23,44082.12,570.1,0.879444
18,TRK00024,941,1362333,2938674.70,6.493056,22,42592.23,705.5,0.857972
42,TRK00057,951,1377066,2933620.12,6.545833,25,57753.94,651.2,0.866139
25,TRK00035,932,1343802,2926212.82,6.495556,19,40952.30,516.8,0.850778

In [33]:
# Truck Utilization Analysis

top_utilized_trucks = truck_summary.sort_values(
    by="utilization_rate",
    ascending=False
).head(10)

print("\nTop 10 Trucks by Utilization Rate:")
display(top_utilized_trucks)

Top 10 Trucks by Utilization Rate:

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
41,TRK00055,977,1417530,2997124.44,6.477778,29,60433.32,689.5,0.890667
32,TRK00044,971,1403922,3045707.57,6.500833,38,69825.23,1080.4,0.885250
28,TRK00039,966,1366732,2904283.89,6.511389,24,47581.13,557.0,0.881583
30,TRK00041,965,1404001,3017320.99,6.509722,25,59685.24,524.7,0.879583
19,TRK00025,963,1370297,2942525.23,6.484722,23,44082.12,570.1,0.879444
39,TRK00053,964,1378108,2990269.38,6.477222,27,50297.23,635.0,0.878889
12,TRK00015,961,1386604,2979377.79,6.497222,21,33711.95,562.5,0.877194
36,TRK00050,956,1338947,2907686.62,6.496389,29,55990.68,687.7,0.872750
0,TRK00001,951,1356397,2896338.17,6.488611,24,51775.99,713.2,0.867139
42,TRK00057,951,1377066,2933620.12,6.545833,25,57753.94,651.2,0.866139

In [3]:
import pandas as pd

# Load Gold Layer tables

customer_summary = pd.read_csv(
    "../Gold/customer_revenue_summary/customer_revenue_summary.csv"
)

driver_summary = pd.read_csv(
    "../Gold/driver_performance_summary/driver_performance_summary.csv"
)

route_summary = pd.read_csv(
    "../Gold/route_summary/route_summary.csv"
)

truck_summary = pd.read_csv(
    "../Gold/truck_summary/truck_summary.csv"
)

print("✅ Gold Layer tables loaded successfully!")

print("\nCustomer Summary:", customer_summary.shape)
print("Driver Summary:", driver_summary.shape)
print("Route Summary:", route_summary.shape)
print("Truck Summary:", truck_summary.shape)

✅ Gold Layer tables loaded successfully!

Customer Summary: (200, 4)
Driver Summary: (150, 10)
Route Summary: (58, 4)
Truck Summary: (92, 9)

In [5]:
# Top 10 Trucks by Revenue

top_trucks = truck_summary.sort_values(
    by="total_revenue",
    ascending=False
).head(10)

print("\nTop 10 Trucks by Revenue:")
display(top_trucks)

Top 10 Trucks by Revenue:

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
32,TRK00044,971,1403922,3045707.57,6.500833,38,69825.23,1080.4,0.885250
82,TRK00107,930,1389705,3022073.78,6.488056,17,31131.25,341.2,0.847111
30,TRK00041,965,1404001,3017320.99,6.509722,25,59685.24,524.7,0.879583
41,TRK00055,977,1417530,2997124.44,6.477778,29,60433.32,689.5,0.890667
39,TRK00053,964,1378108,2990269.38,6.477222,27,50297.23,635.0,0.878889
12,TRK00015,961,1386604,2979377.79,6.497222,21,33711.95,562.5,0.877194
19,TRK00025,963,1370297,2942525.23,6.484722,23,44082.12,570.1,0.879444
18,TRK00024,941,1362333,2938674.70,6.493056,22,42592.23,705.5,0.857972
42,TRK00057,951,1377066,2933620.12,6.545833,25,57753.94,651.2,0.866139
25,TRK00035,932,1343802,2926212.82,6.495556,19,40952.30,516.8,0.850778

In [7]:
# Top 10 Trucks by Utilization Rate

top_utilized_trucks = truck_summary.sort_values(
    by="utilization_rate",
    ascending=False
).head(10)

print("\nTop 10 Trucks by Utilization Rate:")
display(top_utilized_trucks)

Top 10 Trucks by Utilization Rate:

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
41,TRK00055,977,1417530,2997124.44,6.477778,29,60433.32,689.5,0.890667
32,TRK00044,971,1403922,3045707.57,6.500833,38,69825.23,1080.4,0.885250
28,TRK00039,966,1366732,2904283.89,6.511389,24,47581.13,557.0,0.881583
30,TRK00041,965,1404001,3017320.99,6.509722,25,59685.24,524.7,0.879583
19,TRK00025,963,1370297,2942525.23,6.484722,23,44082.12,570.1,0.879444
39,TRK00053,964,1378108,2990269.38,6.477222,27,50297.23,635.0,0.878889
12,TRK00015,961,1386604,2979377.79,6.497222,21,33711.95,562.5,0.877194
36,TRK00050,956,1338947,2907686.62,6.496389,29,55990.68,687.7,0.872750
0,TRK00001,951,1356397,2896338.17,6.488611,24,51775.99,713.2,0.867139
42,TRK00057,951,1377066,2933620.12,6.545833,25,57753.94,651.2,0.866139

In [9]:
# Top 10 Trucks by Maintenance Cost

top_maintenance_trucks = truck_summary.sort_values(
    by="maintenance_cost",
    ascending=False
).head(10)

print("\nTop 10 Trucks by Maintenance Cost:")
display(top_maintenance_trucks)

Top 10 Trucks by Maintenance Cost:

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
57,TRK00073,935,1338563,2872595.75,6.504167,39,76573.99,996.3,0.854361
77,TRK00099,894,1291808,2778323.05,6.506667,34,73231.77,743.7,0.816028
11,TRK00014,886,1240298,2691574.68,6.519722,34,71801.82,940.4,0.808556
20,TRK00026,895,1252565,2712784.82,6.469722,32,70708.48,787.9,0.815500
32,TRK00044,971,1403922,3045707.57,6.500833,38,69825.23,1080.4,0.885250
27,TRK00038,908,1262396,2751437.74,6.508056,31,68989.14,796.4,0.828250
29,TRK00040,860,1178515,2553800.68,6.503611,26,67557.74,665.1,0.783472
24,TRK00033,908,1274427,2738265.04,6.503056,32,67514.43,908.2,0.827444
38,TRK00052,891,1241107,2716175.17,6.514167,31,63757.21,737.3,0.811528
55,TRK00071,911,1269268,2741932.00,6.503333,31,61696.55,761.5,0.831250

In [11]:
# Overall Business KPIs

print("=== OVERALL BUSINESS KPIs ===")

print("\nCustomer Metrics")
print("Total Customers:", len(customer_summary))
print("Total Customer Revenue:",
      customer_summary["annual_revenue"].sum())

print("\nDriver Metrics")
print("Total Drivers:", len(driver_summary))
print("Total Trips Completed:",
      driver_summary["trips_completed"].sum())
print("Total Miles:",
      driver_summary["total_miles"].sum())

print("\nRoute Metrics")
print("Total Routes:", len(route_summary))
print("Total Loads:",
      route_summary["total_loads"].sum())
print("Total Route Revenue:",
      route_summary["total_revenue"].sum())

print("\nTruck Metrics")
print("Total Trucks:", len(truck_summary))
print("Total Truck Trips:",
      truck_summary["trips_completed"].sum())
print("Total Truck Revenue:",
      truck_summary["total_revenue"].sum())

=== OVERALL BUSINESS KPIs ===

Customer Metrics
Total Customers: 200
Total Customer Revenue: 537647349

Driver Metrics
Total Drivers: 150
Total Trips Completed: 83696.0
Total Miles: 119692305.0

Route Metrics
Total Routes: 58
Total Loads: 85410
Total Route Revenue: 262525800.29

Truck Metrics
Total Trucks: 92
Total Truck Trips: 83738
Total Truck Revenue: 257344259.9

In [15]:
#Business Insight Summary
# Top Customer
top_customer = customer_summary.loc[
    customer_summary["annual_revenue"].idxmax()
]

print("\n🏆 Top Customer by Revenue:")
print("Customer ID:", top_customer["customer_id"])
print("Revenue:", top_customer["annual_revenue"])

# Top Driver
top_driver = driver_summary.loc[
    driver_summary["total_revenue"].idxmax()
]

print("\n🏆 Top Driver by Revenue:")
print("Driver ID:", top_driver["driver_id"])
print("Revenue:", top_driver["total_revenue"])

# Top Route
top_route = route_summary.loc[
    route_summary["total_revenue"].idxmax()
]

print("\n🏆 Top Route by Revenue:")
print("Route ID:", top_route["route_id"])
print("Revenue:", top_route["total_revenue"])

# Top Truck
top_truck = truck_summary.loc[
    truck_summary["total_revenue"].idxmax()
]

print("\n🏆 Top Truck by Revenue:")
print("Truck ID:", top_truck["truck_id"])
print("Revenue:", top_truck["total_revenue"])

# Most Utilized Truck
top_utilized_truck = truck_summary.loc[
    truck_summary["utilization_rate"].idxmax()
]

print("\n🚛 Most Utilized Truck:")
print("Truck ID:", top_utilized_truck["truck_id"])
print("Utilization Rate:", top_utilized_truck["utilization_rate"])

🏆 Top Customer by Revenue:
Customer ID: CUST00195
Revenue: 4990599

🏆 Top Driver by Revenue:
Driver ID: DRV00051
Revenue: 2311844.3

🏆 Top Route by Revenue:
Route ID: RTE00016
Revenue: 10069054.22

🏆 Top Truck by Revenue:
Truck ID: TRK00044
Revenue: 3045707.57

🚛 Most Utilized Truck:
Truck ID: TRK00055
Utilization Rate: 0.8906666666666667

In [17]:
#Business Insights Table

business_insights = pd.DataFrame({
    "metric": [
        "Top Customer by Revenue",
        "Top Driver by Revenue",
        "Top Route by Revenue",
        "Top Truck by Revenue",
        "Most Utilized Truck"
    ],
    "entity_id": [
        top_customer["customer_id"],
        top_driver["driver_id"],
        top_route["route_id"],
        top_truck["truck_id"],
        top_utilized_truck["truck_id"]
    ],
    "value": [
        top_customer["annual_revenue"],
        top_driver["total_revenue"],
        top_route["total_revenue"],
        top_truck["total_revenue"],
        top_utilized_truck["utilization_rate"]
    ]
})

display(business_insights)

                    metric  entity_id         value
0  Top Customer by Revenue  CUST00195  4.990599e+06
1    Top Driver by Revenue   DRV00051  2.311844e+06
2     Top Route by Revenue   RTE00016  1.006905e+07
3     Top Truck by Revenue   TRK00044  3.045708e+06
4      Most Utilized Truck   TRK00055  8.906667e-01

In [19]:
import os

os.makedirs("../Gold/business_insights", exist_ok=True)

business_insights.to_csv(
    "../Gold/business_insights/business_insights.csv",
    index=False
)

print("✅ Business Insights saved successfully!")

✅ Business Insights saved successfully!

In [21]:
# Final Business Insights Validation

print("=== BUSINESS INSIGHTS VALIDATION ===")

print("Rows:", len(business_insights))
print("Columns:", len(business_insights.columns))
print("Duplicate Rows:", business_insights.duplicated().sum())
print("Null Values:", business_insights.isnull().sum().sum())

print("\nBusiness Insights:")
display(business_insights)

print("\n✅ Business Insights Validation Completed!")

=== BUSINESS INSIGHTS VALIDATION ===
Rows: 5
Columns: 3
Duplicate Rows: 0
Null Values: 0

Business Insights:

                    metric  entity_id         value
0  Top Customer by Revenue  CUST00195  4.990599e+06
1    Top Driver by Revenue   DRV00051  2.311844e+06
2     Top Route by Revenue   RTE00016  1.006905e+07
3     Top Truck by Revenue   TRK00044  3.045708e+06
4      Most Utilized Truck   TRK00055  8.906667e-01

✅ Business Insights Validation Completed!